services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    admin.uploader_handler:
        class: AdminBundle\Services\UploaderHandler
        arguments: ['test data']
