client:
    resource: "@ClientBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"


    
