<?php

namespace AdminBundle\Repository;

/**
 * DiskyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiskyRepository extends \Doctrine\ORM\EntityRepository
{
}
